server {
listen 80;

# 1. Serve Frontend Static Files
location / {
root /usr/share/nginx/html;
index index.html;
try_files $uri $uri/ /index.html;
}

# 2. Proxy API calls to the Backend on 8080
# Add every base path used in your Swagger here
location ~ ^/(auth|game|admin|locations|users|leaderboard)/ {
proxy_pass http://host.docker.internal:8082;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}